#!/bin/bash

git clone https://github.com/aniko33/lsspace-cli.git
cd lsspace-cli
echo 
printf 'wait... \n'
echo 
pip install -r req.txt
echo ------------------------------
printf 'installation completed \n'
